refactor(lua2dox_filter): format

diff --git a/scripts/lua2dox_filter b/scripts/lua2dox_filter
--- a/scripts/lua2dox_filter
+++ b/scripts/lua2dox_filter
@@ -22,72 +22,69 @@
 LANG=""
 
 ##! \brief test executable to see if it exists
-test_executable(){
-	P_EXE="$1"
-	#########
-	WHICH=`which ${P_EXE}`
-	if test -z "${WHICH}"
-	then
-		echo "not found \"${P_EXE}\""
-	else
-		EXE="${P_EXE}"
-	fi
-	}
+test_executable() {
+  P_EXE="$1"
+  #########
+  WHICH=$(which "$P_EXE")
+  if test -z "${WHICH}"; then
+    echo "not found \"${P_EXE}\""
+  else
+    EXE="${P_EXE}"
+  fi
+}
 
 ##! \brief sets the lua interpreter
-set_lua(){
-	if test -z "${EXE}"; then
-		test_executable '.deps/usr/bin/luajit'
-	fi
+set_lua() {
+  if test -z "${EXE}"; then
+    test_executable '.deps/usr/bin/luajit'
+  fi
 
-	if test -z "${EXE}"; then
-		test_executable 'luajit'
-	fi
+  if test -z "${EXE}"; then
+    test_executable 'luajit'
+  fi
 
-	if test -z "${EXE}"; then
-		test_executable 'lua'
-	fi
+  if test -z "${EXE}"; then
+    test_executable 'lua'
+  fi
 }
 
 ##! \brief makes canonical name of file
-##! 
+##!
 ##! Note that "readlink -f" doesn't work in MacOSX
-##! 
-do_readlink(){
-	pushd . > /dev/null
-	TARGET_FILE=$1
-	
-	cd `dirname $TARGET_FILE`
-	TARGET_FILE=`basename $TARGET_FILE`
-	
-	# Iterate down a (possible) chain of symlinks
-	while [ -L "$TARGET_FILE" ]
-	do
-		TARGET_FILE=`readlink $TARGET_FILE`
-		cd `dirname $TARGET_FILE`
-		TARGET_FILE=`basename $TARGET_FILE`
-	done
-	
-	PHYS_DIR=`pwd -P`
-	RESULT=$PHYS_DIR
-	popd > /dev/null
-	}
+##!
+do_readlink() {
+  pushd . > /dev/null
+  TARGET_FILE=$1
+
+  cd "$(dirname $TARGET_FILE)"
+  TARGET_FILE=$(basename "$TARGET_FILE")
+
+  # Iterate down a (possible) chain of symlinks
+  while [ -L "$TARGET_FILE" ]; do
+    TARGET_FILE=$(readlink "$TARGET_FILE")
+    cd $(dirname "$TARGET_FILE")
+    TARGET_FILE=$(basename "$TARGET_FILE")
+  done
+
+  PHYS_DIR=$(pwd -P)
+  RESULT=$PHYS_DIR
+  popd > /dev/null
+}
 
 ##main
 set_lua
-if test -z "${EXE}"
-then
-	echo "no lua interpreter found"
-	exit 1
+if test -z "${EXE}"; then
+  echo "no lua interpreter found"
+  exit 1
 else
-	BASENAME=`basename "$0"`
-	do_readlink "$0"
-	DIRNAME="${RESULT}"
-		
-	LUASCRIPT="${DIRNAME}/lua2dox.lua ${BASENAME}"
-	#echo "lua[${LUASCRIPT}]"
+  BASENAME=$(basename "$0")
+  do_readlink "$0"
+  DIRNAME="${RESULT}"
 
-	${EXE} ${LUASCRIPT} $@
+  LUASCRIPT="${DIRNAME}/lua2dox.lua ${BASENAME}"
+  #echo "lua[${LUASCRIPT}]"
+
+  ${EXE} ${LUASCRIPT} $@
 fi
-# 
+
 ##eof
